import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import SiteList from "../components/SiteList/SiteList";
import styles from "./customer.module.css";
import { useRouter } from "next/router";
import { trpc } from "../utils/trpc";

const Customer: NextPage = () => {
    const router = useRouter();
    const { customer } = router.query;
    const { data, isLoading } = trpc.categories.getCustomer.useQuery(customer as string);

    console.log(data)

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title={data?.name}>
        <div className={styles.content}>
            {isLoading ? <p>Loading...</p> : <SiteList sites={data?.sites} />}
            
        </div>
      </Layout>
    </>
  );
};

export default Customer;
