import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout/Layout";
import { useState, useEffect } from "react";
import styles from "./global.module.css";
import GlobalTable from "../components/GlobalTable/GlobalTable";
import { trpc } from "../utils/trpc";

const Global: NextPage = () => {
  const { data, isLoading, refetch } = trpc.categories.getAllCases.useQuery();
  console.log(data);

  useEffect(() => {
    setCurrentCase(data);
  }, [data])

  const [currentCase, setCurrentCase] = useState(data);

  const handleSearch = (searchValue:string) => {
    const filteredCases = data?.filter((c) => c.id.includes(searchValue));
    if (searchValue)
      setCurrentCase(filteredCases);
    else 
      setCurrentCase(data);
  }

  const refetchear = () => {
    refetch();
  };

  return (
    <>
      <Head>
        <title>All cases</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="All cases" enableSearch handleSearch={handleSearch}>
        {isLoading ? (
          <div>Loading...</div>
        ) : (
          <div className={styles.content}>
            <GlobalTable cases={currentCase} refetchear={refetchear} />
          </div>
        )}
      </Layout>
    </>
  );
};

export default Global;
