import type { NextPage } from "next";
import Head from "next/head";
import CatCard from "../components/CatCard/CatCard";
import Layout from "../components/Layout/Layout";
import styles from "./index.module.css";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.categories.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Welcome" enableSearch={false}>
        <div className={styles.content}>
          {isLoading ? (
            <div>Loading...</div>
          ) : (
            data?.map((customer) => (
              <CatCard
                key={customer.id}
                title={customer.alt}
                needsAttention={
                  customer.cases.filter((c) => c.atention === true).length
                }
                totalCases={customer.cases.length}
                customerId={customer.id}
              />
            ))
          )}
        </div>
      </Layout>
    </>
  );
};

export default Home;
