import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header/Header";
import NavBar from "../components/NavBar/NavBar";
import CatCard from "../components/CatCard/CatCard";
import Layout from "../components/Layout/Layout";
import styles from "./index.module.css";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.categories.getAll.useQuery();
  console.log(data);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout title="Welcome">
        <div className={styles.content}>
          {isLoading ? (
            <div>Cargando matraka</div>
          ) : (
            data?.map((customer) => (
              <CatCard
                key={customer.id}
                title={customer.alt}
                needsAttention={
                  customer.cases.filter((c) => c.atention === true).length
                }
                totalCases={customer.cases.length}
              />
            ))
          )}
        </div>
      </Layout>
      {/* <div className={styles.gridContainer}>
        <div className={styles.nav}>
          <NavBar customers={data} />
        </div>
        <div className={styles.header}>
          <Header title="Welcome you fuck" />
        </div>
        <div className={styles.content}>
          {isLoading ? (
            <div>Cargando matraka</div>
          ) : (
            data?.map((customer) => (
              <CatCard
                key={customer.id}
                title={customer.alt}
                needsAttention={customer.cases.filter((c) => c.atention === true).length}
                totalCases={customer.cases.length}
              />
            ))
          )}
        </div>
      </div> */}
    </>
  );
};

export default Home;
